### ISSUE TITLE
SAXParseException warning for versions >= 3.0.5

### ISSUE THREAD

**Issue by michael4screen** [monosoul/jooq-gradle-plugin#100]
# Description

When running the `generateJooqClasses` command since version [3.0.5](https://github.com/monosoul/jooq-gradle-plugin/releases/tag/3.0.5) we see the following warning. Code generation still succeeds though. 

`> Task :generateJooqClasses
org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 23; cvc-complex-type.2.4.d: Ungültiger Content wurde beginnend mit Element 'matchers' gefunden. An dieser Stelle wird kein untergeordnetes Element erwartet.
cvc-complex-type.2.4.d: Ungültiger Content wurde beginnend mit Element 'matchers' gefunden. An dieser Stelle wird kein untergeordnetes Element erwartet.`

Appears with config reduced to only:

        jooq {
            withContainer {
                image {
                    name = "postgis/postgis:11-2.5"
                }
            }
        }

**Comment by monosoul** [comment]
Hey @michael4screen , thanks for letting me know. Do you use the plugin with built-in jooq or do you configure another version with `jooqCodegen` config?

**Comment by monosoul** [comment]
Oh, nvm, I think I found the issue there
