### ISSUE TITLE
gradle cache misses due to generatorConfig marked as @Input

### ISSUE THREAD

**Issue by 5V715** [monosoul/jooq-gradle-plugin#127]
would it be possible to remove the `@Input` annotation [here](https://github.com/monosoul/jooq-gradle-plugin/blob/main/src/main/kotlin/dev/monosoul/jooq/GenerateJooqClassesTask.kt#L91). it is actually not really an input field since it's value is derived. it explicitly states that 

> Avoid changing manually, use [usingJavaConfig] or [usingXmlConfig] instead.

so maybe not even expose it (private).  

my assumption is that the use of the lambda expression is causing this glitch
<img width="1343" alt="Screenshot 2023-07-12 at 19 12 59" src="https://github.com/monosoul/jooq-gradle-plugin/assets/822608/727f53d6-2478-49ad-9c17-c58c1d02fe4f">

Thank you for your great work - highly appreciated 🙇

**Comment by monosoul** [comment]
Hey @5V715 , this annotation is there exactly to make sure cache is invalidated properly when configuration changes. This is the only property that stores the actual codegen config. It shouldn't change though unless you changed the configuration somehow.

Could you provide more details of your setup? Would be great to have full codegen task configuration sample.

**Comment by monosoul** [comment]
If you could provide a full reproducer of the issue, that would be most helpful.
