### ISSUE TITLE
Exclude Flyway Step

### ISSUE THREAD

**Issue by MEnnabah** [monosoul/jooq-gradle-plugin#190]
First of all, thank you very much for this plugin. We have been using it extensively and it got us using jOOQ quickly with a seamless DX.

We're using this plugin mainly to generate jOOQ classes for a database that belongs to the application, where the migration scripts live in the source code.

We're now adding another database (we followed the [Multi-database setup](https://github.com/monosoul/jooq-gradle-plugin?tab=readme-ov-file#multi-database-setup) example of the README.md). However, that database doesn't belong to the application, and is readonly access.

When we run the task, we get the following error:
```
Found non-empty schema(s) "public" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
```

We tried customising the Flyway properties, but it seems they're being ignored. Here's an example of what we tried:
```groovy
flywayProperties.put("flyway.baselineVersion", "2") // our migrations only has version 1
flywayProperties.put("baselineVersion", "2")
flywayProperties.put("flyway.enabled", "false") // Unknown configuration property: flyway.enabled
flywayProperties.put("enabled", "false")
```

Here's how the task looks like:

```groovy
tasks.register("generateForExternalDatabase", GenerateJooqClassesTask.class) {
    basePackageName.set("com.sample.database.external")
    flywayProperties.put("flyway.baselineVersion", "2")
    flywayProperties.put("flyway.enabled", "false")
    includeFlywayTable.set(false)
    withoutContainer {
        db {
            username = ""
            password = ""
            name = ""
            host = ""
            port = 5432
        }
    }
}
```

When we run the task with a higher baseline version, or flyway disabled, we still get the same error of non-empty schema. Is it possible to disable Flyway for a single database configuration in a multi-database setup?

**Comment by MEnnabah** [comment]
The `flywayProperties` needs to be set:

```java
setFlywayProperties(Map.of("flyway.baselineVersion", "2"))
```

**Comment by monosoul** [comment]
That doesn't seem right, setting properties with `flywayProperties.put` should work too, there's a test for that :thinking:
