### ISSUE TITLE
Add option for keeping alive Testcontainers after finishing generateJooqClasses task

### ISSUE THREAD

**Issue by SightStudio** [monosoul/jooq-gradle-plugin#210]
I think adding an option to allow the Testcontainers to be maintained
after the 'generateJooqClasses' task is completed is good.

This can allow us to view the entire schema from ddl script (including the tables I created locally) in another RDBMS tool. (eg dbeaver)

We can use **DDLDatabase** in Intellij to see ERD with DDL alone, but this is not satisfactory and not enough.
(And it is inconvenient.)

<img width="1663" alt="스크린샷 2024-07-14 오후 1 23 01" src="https://github.com/user-attachments/assets/91187fba-589f-434e-be61-02c44156a510">

## suggestion
----

here's my suggestion, can I make a PR for this?

https://github.com/monosoul/jooq-gradle-plugin/blob/main/src/main/kotlin/dev/monosoul/jooq/settings/JooqDockerPluginSettings.kt#L23

add option to WithContainer class 

```kotlin
class WithContainer private constructor(
        override val database: Database.Internal,
        @get:Nested internal val image: Image,

        // add option for WithContainer (of course, default must be true)
        private val dropContainerAfterComplete: Boolean = true,
    ) : JooqDockerPluginSettings(),
        DbAware<Database.Internal>,
        ImageAware {
        private constructor(database: Database.Internal) : this(database, Image(database))
        constructor(customizer: Action<WithContainer> = Action<WithContainer> { }) : this(Database.Internal()) {
            customizer.execute(this)
        }

        override fun runWithDatabaseCredentials(
            classloaders: CodegenClasspathAwareClassLoaders,
            block: (CodegenClasspathAwareClassLoaders, DatabaseCredentials) -> Unit,
        ) {
            val dbContainer =
                GenericDatabaseContainer(
                    image = image,
                    database = database,
                    jdbcAwareClassLoader = classloaders.buildscriptInclusive,
                ).also { it.start() }

            try {
                block(
                    classloaders,
                    DatabaseCredentials(
                        jdbcDriverClassName = dbContainer.driverClassName,
                        jdbcUrl = dbContainer.jdbcUrl,
                        username = dbContainer.username,
                        password = dbContainer.password,
                    ),
                )
            } finally {
                // stop container if option is true
                if (dropContainerAfterComplete) {
                    dbContainer.stop()
                }
            }
        }

        override fun copy(): WithContainer =
            WithContainer(
                database = database.run { copy(jdbc = jdbc.copy()) },
                image = image.copy(),
                dropContainerAfterComplete = dropContainerAfterComplete
            )

           // ...
    }
```

**Comment by monosoul** [comment]
Hey @SightStudio , thanks for the suggestion. Just adding the condition around `dbContainer.stop()` call wouldn't prevent the container from being stopped in some cases (e.g. when Gradle runs without a daemon, in this case [ryuk](https://hub.docker.com/r/testcontainers/ryuk) would kill the container), [the container has to also be declared as reusable](https://java.testcontainers.org/features/reuse/#how-to-use-it) then.
You should also expose this option via properties (see [PropertiesReader](https://github.com/monosoul/jooq-gradle-plugin/blob/main/src/main/kotlin/dev/monosoul/jooq/settings/PropertiesReader.kt)).
And then cover the change with tests.

Tbh, I'm not sure if it worth the effort, given that the plugin's purpose is not to just run migrations, but generate code. I.e. validation migration results shouldn't be the plugin's responsibility IMO. Instead you can just add a task to your own buildscript to spin up a container and apply migrations to it.

**Comment by SightStudio** [comment]
@monosoul 

you're right. on second thought it'll add complexity to this plugin.

I'll close this issue thanks for feedback.
