### ISSUE TITLE
Possibility to specify source set

### ISSUE THREAD

**Issue by Fadelis** [monosoul/jooq-gradle-plugin#213]
Currently when generating jOOQ sources it is hardcoded to use the `main` source set https://github.com/monosoul/jooq-gradle-plugin/blob/58f4d40bed28e1ac51856252aa1bdb8972146225/src/main/kotlin/dev/monosoul/jooq/JooqDockerPlugin.kt#L45

But there are some cases where you'd want to change that, for example when using [library features](https://docs.gradle.org/current/userguide/feature_variants.html) and you have a different source set for some feature for which you'd want to generate the jooq sources. So it would be a nice addition to be able to configure this parameter.

**Comment by monosoul** [comment]
@Fadelis you can now set the target source set in the codegen task config with `targetSourceSet` property.

**Comment by Fadelis** [comment]
Yes, it works as expected 👍  Thanks for lighting fast turnaround! ⚡
