### ISSUE TITLE
Request for generateOnBuild Flag to enable Manual jOOQ Class Generation

### ISSUE THREAD

**Issue by 7u4** [monosoul/jooq-gradle-plugin#229]
Thank you for yours great work.

The plugin currently generates classes automatically on every build. For teams that check these generated classes into Git. We understand that changes in the Data Access Layer (DAL) are critical issues, and we want to avoid unnecessary build time. To address this, I propose the addition of a generateOnBuild flag that allows for manual generation of jOOQ classes.

Use Case:

Critical DAL Changes: Since modifications in the DAL can have significant implications, controlling when these classes are generated is essential to ensure that only intentional updates are made.

Build Performance: Automatic generation can slow down build times, especially in large projects with complex database schemas. A manual generation option would allow teams to optimize their build process and focus on critical changes.

https://blog.jooq.org/look-no-further-the-final-answer-to-where-to-put-generated-code/

**Comment by monosoul** [comment]
> Build Performance: Automatic generation can slow down build times, especially in large projects with complex database schemas. A manual generation option would allow teams to optimize their build process and focus on critical changes.

Consider using Gradle build cache instead. The plugin makes sure to generate stable cache keys, so cache generated in CI can be used on local dev machines just fine too.

> Critical DAL Changes: Since modifications in the DAL can have significant implications, controlling when these classes are generated is essential to ensure that only intentional updates are made.

From my POV, the source of truth for generated classes here are: the migrations + the plugin configuration. You track both with VCS, hence you don't have to track the artifacts code generation produces.
With manual code generation it is too easy to accidentally forget to generate jOOQ classes after adding new DB migrations (that happened to me personally), it is error prone.

Sorry, but this change request goes very much against what the plugin stands for, so I won't going to implement that.
