### ISSUE TITLE
Disable autoGeneration

### ISSUE THREAD

**Issue by vendelieu** [monosoul/jooq-gradle-plugin#242]
Hey there, first of all thank you for you plugin!
I just wanted to ask is this possible to disable jooqCodeGen for every build? (to hit manually when needed)

**Comment by monosoul** [comment]
Hi! It is technically possible, but I wouldn't recommend that. What's your use case?

**Comment by vendelieu** [comment]
I would love to have something similar to nu.studer's > `generateSchemaSourceOnCompilation.set(false)`

**Comment by monosoul** [comment]
@vendelieu you can do something like that in your buildscript:

```kotlin
tasks.generateJooqClasses {
    onlyIf {
        gradle.startParameter.taskNames.contains(it.name) || gradle.taskGraph.hasTask("assemble")
    }
}
```

Then `generateJooqClasses` task will only be executed if it was explicitly specified in the list of tasks to execute or if `assemble` task was called.
