### ISSUE TITLE
Configuration cache compatibility

### ISSUE THREAD

**Issue by bonitao** [monosoul/jooq-gradle-plugin#46]
When running with https://docs.gradle.org/current/userguide/configuration_cache.html, this will warn:

`org.gradle.api.InvalidUserCodeException: Invocation of 'Task.project' by task ':libs.pbtables:generateJooqClasses' at execution time is unsupported.`

The stack trace points to the two locations using project in the GenerateJooqClassesTasks.kt file:

https://github.com/monosoul/jooq-gradle-plugin/blob/main/src/main/kotlin/dev/monosoul/jooq/GenerateJooqClassesTask.kt#L206
https://github.com/monosoul/jooq-gradle-plugin/blob/main/src/main/kotlin/dev/monosoul/jooq/GenerateJooqClassesTask.kt#L123

Guidance for the fix is here: https://docs.gradle.org/7.4.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

Thanks for the nice fork btw!

**Comment by monosoul** [comment]
Thanks for letting me know, I'll have a look!

**Comment by monosoul** [comment]
@bonitao this version should work with configuration cache: https://plugins.gradle.org/plugin/dev.monosoul.jooq-docker/1.3.5
