### ISSUE TITLE
WithContainer doesnt spin up the correct container for versions >=1.3.5

### ISSUE THREAD

**Issue by michael4screen** [monosoul/jooq-gradle-plugin#59]
First of all big big appreciation to you for forking and maintaining this plugin. 
We still sticked to the last version of the original plugin until now. 
Today I discovered your fork and could migrate easily.

# Description 

I faced one issue though. We are using `WithContainers` block with postgis database image for code generation. 
This is working fine up to version 1.3.5 but not with versions >= 1.3.5.
We are applying following configuration:

```
jooq {
    withContainer {
        image {
            name = "postgis/postgis:11-2.5"
        }
    }
}
```

# Expected Behaviour

A container for image `postgis/postgis:11-2.5` is spun up. 

# Actual Behaviour

A container for image `postgres:14.4-alpine` is spun up.

**Comment by monosoul** [comment]
Hey @michael4screen , I need a few extra details from you.

1. What Gradle version do you use?
2. Do you apply any configuration to `generateJooqClasses` task? If yes, can you share a configuration snippet with me?
3. Do you use configuration cache in Gradle?

**Comment by monosoul** [comment]
If you can provide a small reproducer that would be great. I tried to reproduce it, but with no luck.

**Comment by michael4screen** [comment]
Hi @monosoul ,

Thanks for the quick response.
I'm running gradle version `7.5.1`. No configuration cache.
Following config for `generateJooqClasses`:

```
generateJooqClasses {
        basePackageName.set("com.fourscreen...")
        inputDirectory.setFrom(project.files("src/main/resources/db/migration"))
        outputDirectory.set(project.layout.buildDirectory.dir("generated/sources/jooq/java/main"))
        includeFlywayTable.set(false)
        usingJavaConfig {
            database.withExcludes("spatial_ref_sys | geography_columns | geometry_columns | raster_columns | raster_overviews")
            generate.withJavaTimeTypes(true)
            generate.withDeprecated(false)
            database.withTableValuedFunctions(false)
            database.withIncludeRoutines(false)
            database.withIncludeUDTs(false)
            database.withForcedTypes(
                    new org.jooq.meta.jaxb.ForcedType()
                            .withConverter("com.fourscreen.supply.provisioningservice.dataaccess.jooq.converter.JooqTimestampConverter")
                            .withUserType("java.time.Instant")
                            .withIncludeExpression(".*")
                            .withIncludeTypes("timestamp.*zone")
            )
        }
    }
```

 I will try to provide a reproducer.

**Comment by monosoul** [comment]
Hey @michael4screen , thanks for providing the code block! Looking at it I realized you're using a Groovy buildscript, while I was trying to reproduce it with a Kotlin buildscript. I was able to reproduce the issue using Groovy, I'll see how I can fix it.

**Comment by monosoul** [comment]
Hmm, the issue I found seems to be reproducible with version 1.3.4. as well. @michael4screen could you still try to provide a reproducer, please?
Also, could you check if you call the method `withContainer` more than 1 time in your build script?

**Comment by michael4screen** [comment]
@monosoul yes, now it works. Thanks a lot !
